### ISSUE TITLE
Console popup

### ISSUE THREAD

**Issue by ctrueden** [apposed/jaunch#24]
The native launcher currently pops up a Command Prompt console. The Jaunch Kotlin code should probably use `javaw.exe` (not `java.exe`) when querying the Java installation's system properties. Needs further testing.

**Comment by hinerm** [comment]
I did some initial playing around to just figure out how to get rid of the console window for now. The general idea was to set the `mwindows` option so that it would launch as a standalone app without a console window.

Notes on things that don't work:
* Adding `linkerOpts("-mwindows")` in the `build.gradle.kts` - would only affect the kotlin launchers and not the C launcher, and unnecessary if the C launcher is in windows mode
* Adjusting the `Makefile`, e.g. adding `LDFLAGS = -mwindows`, because we're not actually using the `Makefile` but running a command

What did work:
```diff
--- a/bin/compile-launcher.sh
+++ b/bin/compile-launcher.sh
@@ -44,6 +44,6 @@ case "$(uname)" in
     compile gcc -o build/launcher-macos-x64 -framework CoreFoundation -target x86_64-apple-macos10.12 &&
     (set -x; lipo -create -output build/launcher build/launcher-macos-x64 build/launcher-macos-arm64)
     ;;
-  MINGW*|MSYS*) compile gcc -o build/launcher-windows-x64.exe ;;
+  MINGW*|MSYS*) compile gcc -o build/launcher-windows-x64.exe -mwindows ;;
   *) compile gcc -o build/launcher ;;
 esac
```

Side note: I don't really understand the second `build/launcher` line for Windows.. is it actually doing anything?
