### ISSUE TITLE
Variable interpolation not working?

### ISSUE THREAD

**Issue by hinerm** [apposed/jaunch#59]
It seems that there [is logic](https://github.com/apposed/jaunch/blob/5f573152532946120191c9598de3b0e086b47393/src/commonMain/kotlin/main.kt#L107-L108) to interpolate variables with [@{var} syntax](https://github.com/apposed/jaunch/blob/5f573152532946120191c9598de3b0e086b47393/src/commonMain/kotlin/vars.kt#L42) however I wasn't able to get it to work.

For example if I edit `fiji.toml` like so:

```toml
jvm.memory='5g'

jvm.max-heap = '@{jvm.memory}'
```

I get the error:
```
Invalid maximum heap size: -Xmx@{jvm.memory}
```

**Comment by ctrueden** [comment]
It's intended for lists, but in your example, `jvm.memory` is a string. The main purpose of that feature is to support the launch-Java-from-Python-via-JPype mode; see the `--python`-related config in `fiji.toml` for an illustration.

**Comment by ctrueden** [comment]
If you just want to use a regular variable, use `${...}` rather than `@{...}`.

**Comment by ctrueden** [comment]
Also, only some keys get interpolated right now, and `jvm.max-heap` might not be one of them.

**Comment by hinerm** [comment]
>Also, only some keys get interpolated right now, and jvm.max-heap might not be one of them.

Seems like it isn't, since this also doesn't work:

```toml
jvm.memory='5g'

jvm.max-heap = '${jvm.memory}'
```

Where is the logic defining which keys are interpolated?

**Comment by hinerm** [comment]
or maybe there just isn't intra-variable interpolation

**Comment by hinerm** [comment]
>or maybe there just isn't intra-toml interpolation

yeah I was able to get it to do what I wanted now

**Comment by ctrueden** [comment]
> Where is the logic defining which keys are interpolated?

In `vars.kt`. The `Vars` class has a `calculate` method, filters the given lines by the current set of hints (via the `String.evaluate` add-on function). Then, for those lines whose rules all match, variables are `interpolate`d.

Via the "Find Usages" feature of IntelliJ on the `calculate` function, we can see which fields get interpolated in this way:
* `main.kt`: `modes` and `directives`
* `jvm.kt`: `root-paths`, `libjvm-suffixes`, `distros-allowed`, `distros-blocked`, `os-aliases`, `arch-aliases`, `classpath`, `runtime-args`, `main-class`, `main-args`
* `python.kt`: `root-paths`, `lib-suffixes`, `runtime-args`, `script-path`, `main-args`

The other place that `interpolate` gets called is from the `interpolateInto` function of `Vars`, which is used for the final construction of runtime args and main args, so that the `@{...}` injection works.

Note that all the above items are list keys, not scalar keys. We could add variable interpolation for scalar keys as well, but I didn't have a use case for it yet when constructing all the various TOML files.
