### ISSUE TITLE
Launch Java via Python

### ISSUE THREAD

**Issue by ctrueden** [apposed/jaunch#6]
It would be very useful for Fiji if Jaunch supported discovery of `libpython` also, and launching Java from inside a Python interpreter via the [scyjava](https://github.com/scijava/scyjava) project, which uses JPype. Then Fiji's CPython script language could be used more easily.

**Comment by Thrameos** [comment]
As mentioned before operating python within the jvm was demostrated in epypj.  But that branch remains abandoned because no users were willing to help with the required testing that would be required for release, and my organization directed me towards other priorities.

If you just want to launch the shell (not able to have a front end to probe python from the java side) that code remains in the epypj branch if someone wants to make a PR and add the front end required to allow command line arguments to pass through to Python.  Unfortunately without a compelling need my organization was not willing to fund it.

**Comment by ctrueden** [comment]
With cfd70d8fb2ce7c07f805f89cb79d344b8cb05e1b, this now works! :tada:
