### ISSUE TITLE
Squash multiple memory options

### ISSUE THREAD

**Issue by ctrueden** [apposed/jaunch#7]
The ImageJ Launcher keeps only the last memory option for the `-Xm*` flags.

```c
 * If passing -Xmx=99999999g -Xmx=37m to Java, the former still triggers an
 * error. So let's keep only the last, so that the command line can override
 * invalid settings in jvm.cfg.
```

Should Jaunch do this?

**Comment by hinerm** [comment]
I'm trying to imagine the user that would benefit from this ability.

If the user has to start from the command line *with a manual memory flag* to get back to the UI to run `Memory and Threads` again to fix their memory setting, is that any easier than expecting them to edit the `fiji.cfg` themselves if it's broken?

Currently, `Memory and Threads` just tells people to delete their `ImageJ.cfg` if their next restart doesn't work. But I'm skeptical of a user remembering a message that was given to them while the app was running.

Enabling this behavior won't help someone running by double-clicking the app - they still won't get an indication of the nature of the failure until they try launching from a terminal.

Personally I'd be happy if Jaunch just provided a hint to edit the `app.cfg` when failing due to being unable to allocate memory for the JVM.
